#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /usr/local/bin/kube-register
    permissions: "0755"
    owner: root
    content: |
      #!/bin/sh

      . /etc/sysconfig/heat-params
      master_url=http://${KUBE_MASTER_IP}:8080
      nova_instance_name=$(hostname -s)

      # wait for master api
      until curl -o /dev/null -sf "${master_url}/healthz"; do
        echo "waiting for kubernetes master"
        sleep 1
      done

      if [ "$1" = "-u" ]; then
      echo "unregistering minion $nova_instance_name"
      kubectl -s ${master_url} delete node/$nova_instance_name
      else
      echo "registering minion $nova_instance_name"
      cpu=$(($(nproc) * 1000))
      memory=$(awk '/MemTotal: /{print $2 * 1024}' /proc/meminfo)

      cat <<EOF | kubectl create -s ${master_url} -f-
      apiVersion: v1
      id: $nova_instance_name
      kind: Node
      resources:
        capacity:
          cpu: $cpu
          memory: $memory
      metadata:
        name: $nova_instance_name
      spec:
         externalID: $nova_instance_name
      EOF
      fi
