- hosts: all
  tasks:
    - include_vars: container-builder-vars.yaml

    - name: "Build magnum images"
      block:
        - name: "Build {{ magnum_repository }}/{{ item.name }}:{{ item.tag }} image"
          docker_image:
            path: "{{ magnum_src_dir }}/dockerfiles/{{ item.name }}"
            name: "{{ magnum_repository }}/{{ item.name }}"
            tag: "{{ item.tag }}"
            push: no
          with_items: "{{ magnum_images }}"
          retries: 10

    - name: "Build kubernetes images"
      block:
        - name: "Build {{ magnum_repository }}/{{ item.name }}:{{ item.tag }} image"
          docker_image:
            path: "{{ magnum_src_dir }}/dockerfiles/{{ item.name }}"
            name: "{{ magnum_repository }}/{{ item.name }}"
            tag: "{{ kubernetes_version }}"
            buildargs:
              KUBE_VERSION: "{{ kubernetes_version }}"
            push: no
          with_items: "{{ kubernetes_images }}"
          retries: 10
