magnum_src_dir: "src/git.openstack.org/openstack/magnum"

magnum_repository: openstackmagnum
kubernetes_version: v1.11.6
kubernetes_images:
  - name: kubernetes-apiserver
  - name: kubernetes-controller-manager
  - name: kubernetes-kubelet
  - name: kubernetes-scheduler
  - name: kubernetes-proxy

magnum_images:
  - name: heat-container-agent
    tag: stein-dev
