- hosts: all
  tasks:
    - include_vars: container-builder-vars.yaml

    - name: Push images to DockerHub
      block:
        - command: docker login -u {{ magnum_docker_login.user }} -p {{ magnum_docker_login.password }}
          no_log: True
          retries: 5
        - command: docker push {{ magnum_repository }}/{{ item.name }}:{{ item.tag }}
          with_items: "{{ magnum_images }}"
          retries: 10
        - command: docker push {{ magnum_repository }}/{{ item[1].name }}:{{ item[0].version }}
          with_nested:
            - "{{ kubernetes_versions }}"
            - "{{ kubernetes_images }}"
          retries: 10
        - command: docker push {{ magnum_repository }}/helm-client:{{ item.version }}
          with_items: "{{ helm_versions }}"
          retries: 10
        - command: docker push {{ magnum_repository }}/cluster-autoscaler:v{{ item.version }}
          with_items: "{{ cluster_autoscaler_versions }}"
          retries: 10
