magnum_src_dir: "src/opendev.org/openstack/magnum"

magnum_repository: openstackmagnum

magnum_images:
  - name: heat-container-agent
    tag: ussuri-dev

helm_versions:
  - version: v2.16.6
  - version: v3.2.0

cluster_autoscaler_versions:
  - version: 1.16.5
  - version: 1.17.2
  - version: 1.18.1
